package org.x.server.mobile;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-19T14:20:26.221+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "QgService", 
                  wsdlLocation = "http://10.58.24.126:801/QgService.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class QgService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QgService");
    public final static QName QgServiceSoap12 = new QName("http://tempuri.org/", "QgServiceSoap12");
    public final static QName QgServiceSoap = new QName("http://tempuri.org/", "QgServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.58.24.126:801/QgService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QgService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.58.24.126:801/QgService.asmx?WSDL");
           }
        WSDL_LOCATION = url;
    }

    public QgService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QgService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QgService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns QgServiceSoap
     */
    @WebEndpoint(name = "QgServiceSoap12")
    public QgServiceSoap getQgServiceSoap12() {
        return super.getPort(QgServiceSoap12, QgServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QgServiceSoap
     */
    @WebEndpoint(name = "QgServiceSoap12")
    public QgServiceSoap getQgServiceSoap12(WebServiceFeature... features) {
        return super.getPort(QgServiceSoap12, QgServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns QgServiceSoap
     */
    @WebEndpoint(name = "QgServiceSoap")
    public QgServiceSoap getQgServiceSoap() {
        return super.getPort(QgServiceSoap, QgServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QgServiceSoap
     */
    @WebEndpoint(name = "QgServiceSoap")
    public QgServiceSoap getQgServiceSoap(WebServiceFeature... features) {
        return super.getPort(QgServiceSoap, QgServiceSoap.class, features);
    }

}
